baseURL = "https://somax.github.io"
title = "So'Blog"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "zh"

[params.info]
description = "知识就像空气，学习如同呼吸。"
title404 = "四零四。空。"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Somax"
startYear = "2018"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
archiveDateFormat = "01-02"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","taxonomy_cloud","recent_posts"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = "somax"
email = "somaxj@163.com"
# facebook = "somax"
github = "somax"
# gitlab = "somax"
# instagram = "somax"
# linkedin = "somax"
# twitter = "somax"
# telegram = "somax"
# google_scholar = "qc6CJjYAAAAJ"

[params.comments]
enable = false

[params.comments.staticman]
enable = true
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2

[params.comments.staticman.github]
username = "somax"
repository = "soblog"
branch = "master"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"


[permalinks]
page = "/:slug/"
# post = "/:year/:month/:slug/"

[[menu.main]]
# name = "Github"
# weight = -10
# identifier = "repository"
# url = "https://github.com/somax/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.zh]
lang = "zh"
languageName = "Chinese"
weight = 1


